apiVersion: v1

kind: Pod

metadata:
  name: postgres-app-pod
  labels:
    name: postgres-pod
    app: demo-voting-app

spec:
  containers:
    - name: postgres
      image: postgres:9.4
      port:
        - containerPort: 5432